/**
 * @file TiffReader.cpp
 * @brief Implementation of the TiffReader class for reading TIFF image files
 * and sequences, including thresholding capabilities. Handles various
 * TIFF formats and integrates with AMReX MultiFabs.
 *
 * @details Includes logic to handle tiled/stripped images and different
 * data types. Contains a workaround to assume LSB FillOrder for
 * 1-bit TIFFs generated by certain tools (like Python's tifffile)
 * that may not explicitly write the FillOrder tag or pack bits
 * differently from the standard default.
 */

// Add this include if you haven't already, for OpenMP directives
#include <omp.h>

// --- Other standard and library includes ---
#include "TiffReader.H" // Ensure this header defines the class and enum
#include <tiffio.h>  // libtiff C API Header
#include <memory>    // For std::unique_ptr
#include <vector>
#include <string>
#include <stdexcept>
#include <limits>
#include <cmath>
#include <sstream>   // Needed for std::ostringstream
#include <cstring>   // For std::memcpy (in helper)
#include <algorithm> // For std::min/max
#include <iomanip>   // For std::setw, std::setfill
#include <map>       // For attributes (if keeping)

// --- AMReX Includes ---
#include <AMReX_Print.H>
#include <AMReX_Box.H>
#include <AMReX_IntVect.H>
#include <AMReX_iMultiFab.H>
#include <AMReX_GpuContainers.H> // For amrex::The_Pinned_Arena? Optional.
#include <AMReX_Extension.H>
#include <AMReX_GpuQualifiers.H>
#include <AMReX_Utility.H>         // Included for AMREX_ALWAYS_ASSERT, amrex::Verbose, amrex::SetVerbose
#include <AMReX_ParallelDescriptor.H> // For IOProcessor, Barrier, Bcast, MyProc, Communicator
#include <AMReX_MFIter.H>          // Needed for MFIter
#include <AMReX_Array4.H>          // Needed for Array4 access
#include <AMReX_Loop.H>            // For LoopOnCpu / amrex::ParallelFor


namespace OpenImpala {

//================================================================
// Anonymous namespace for internal helpers
//================================================================
namespace {

// RAII wrapper for TIFF* handle
struct TiffCloser {
    void operator()(TIFF* tif) const {
        if (tif) TIFFClose(tif);
    }
};
using TiffPtr = std::unique_ptr<TIFF, TiffCloser>;

// Helper to interpret raw bytes based on TIFF metadata (for BPS >= 8)
// Returns value cast to double for threshold comparison
AMREX_GPU_HOST_DEVICE AMREX_FORCE_INLINE
double interpretBytesAsDouble(const unsigned char* byte_ptr,
                              uint16_t bits_per_sample,
                              uint16_t sample_format)
{
    // Ensure bits_per_sample is a multiple of 8 for this function
    // Note: This function is NOT called for 1-bit data in the corrected reader logic
    if (bits_per_sample < 8 || (bits_per_sample % 8 != 0) ) return 0.0;

    size_t bytes_per_sample = bits_per_sample / 8;
    double value = 0.0;

    switch (sample_format) {
        case SAMPLEFORMAT_UINT:
            if (bytes_per_sample == 1) {
                uint8_t val; std::memcpy(&val, byte_ptr, sizeof(val)); value = static_cast<double>(val);
            } else if (bytes_per_sample == 2) {
                uint16_t val; std::memcpy(&val, byte_ptr, sizeof(val)); value = static_cast<double>(val);
            } else if (bytes_per_sample == 4) {
                uint32_t val; std::memcpy(&val, byte_ptr, sizeof(val)); value = static_cast<double>(val);
            } else if (bytes_per_sample == 8) {
                uint64_t val; std::memcpy(&val, byte_ptr, sizeof(val)); value = static_cast<double>(val);
            } // Add else? Error/warning?
            break;
        case SAMPLEFORMAT_INT:
             if (bytes_per_sample == 1) {
                int8_t val; std::memcpy(&val, byte_ptr, sizeof(val)); value = static_cast<double>(val);
            } else if (bytes_per_sample == 2) {
                int16_t val; std::memcpy(&val, byte_ptr, sizeof(val)); value = static_cast<double>(val);
            } else if (bytes_per_sample == 4) {
                int32_t val; std::memcpy(&val, byte_ptr, sizeof(val)); value = static_cast<double>(val);
            } else if (bytes_per_sample == 8) {
                int64_t val; std::memcpy(&val, byte_ptr, sizeof(val)); value = static_cast<double>(val);
            } // Add else?
            break;
        case SAMPLEFORMAT_IEEEFP:
             if (bytes_per_sample == 4) {
                // Ensure float is standard size
                static_assert(sizeof(float) == 4, "Float size mismatch");
                float val; std::memcpy(&val, byte_ptr, sizeof(val)); value = static_cast<double>(val);
            } else if (bytes_per_sample == 8) {
                 // Ensure double is standard size
                static_assert(sizeof(double) == 8, "Double size mismatch");
                double val; std::memcpy(&val, byte_ptr, sizeof(val)); value = val; // Direct assignment
            } // Add else?
            break;
        default:
            // Consider adding a warning or error for unsupported sample formats if necessary
            value = 0.0; // Default for unsupported format
            break;
    }
    return value;
}

// Helper to generate filename for sequences
std::string generateFilename(const std::string& base, int index, int digits, const std::string& suffix) {
     std::ostringstream ss;
     ss << base << std::setw(digits) << std::setfill('0') << index << suffix;
     return ss.str();
}

} // end anonymous namespace


//================================================================
// Constructors
//================================================================
TiffReader::TiffReader() :
    m_width(0), m_height(0), m_depth(0),
    m_bits_per_sample(0), m_sample_format(SAMPLEFORMAT_UINT), m_samples_per_pixel(1),
    m_fill_order(FILLORDER_MSB2LSB), // Initialize fill order default to standard TIFF default
    m_is_read(false), m_is_sequence(false), m_start_index(0), m_digits(1)
{}

TiffReader::TiffReader(const std::string& filename) : TiffReader()
{
    // Constructor for single stack file
    m_filename = filename; // Store filename immediately
    if (!readFile(filename)) {
        // Error message handled within readFile
        throw std::runtime_error("TiffReader(filename): Failed to read metadata from file: " + filename);
    }
}

TiffReader::TiffReader(
    const std::string& base_pattern,
    int num_files,
    int start_index,
    int digits,
    const std::string& suffix) : TiffReader()
{
    // Constructor for sequence files
    m_base_pattern = base_pattern;
    m_start_index = start_index;
    m_digits = digits;
    m_suffix = suffix;
    if (!readFileSequence(base_pattern, num_files, start_index, digits, suffix)) {
         // Error message handled within readFileSequence
         throw std::runtime_error("TiffReader(sequence): Failed to read metadata for sequence: " + base_pattern);
    }
}

//================================================================
// Metadata Getters
//================================================================
int TiffReader::width() const { return m_width; }
int TiffReader::height() const { return m_height; }
int TiffReader::depth() const { return m_depth; }
int TiffReader::bitsPerSample() const { return m_bits_per_sample; }
int TiffReader::sampleFormat() const { return m_sample_format; }
int TiffReader::samplesPerPixel() const { return m_samples_per_pixel; }
bool TiffReader::isRead() const { return m_is_read; }
uint16_t TiffReader::getFillOrder() const { return m_fill_order; } // Added getter

amrex::Box TiffReader::box() const {
    if (!m_is_read) { return amrex::Box(); } // Return empty box if not read
    // AMReX Box is inclusive: (low_corner, high_corner)
    return amrex::Box(amrex::IntVect::TheZeroVector(), // Low corner is (0,0,0)
                      amrex::IntVect(m_width - 1, m_height - 1, m_depth - 1)); // High corner
}

//================================================================
// readFile Method (Single Stack File)
//================================================================
bool TiffReader::readFile(const std::string& filename)
{
    m_is_sequence = false; m_filename = filename; m_base_pattern = "";
    // Variables local to Rank 0 for reading
    int width_r0=0, height_r0=0, depth_r0=0;
    uint16_t bps_r0=0, fmt_r0=SAMPLEFORMAT_UINT, spp_r0=1;
    uint16_t fill_order_r0 = FILLORDER_MSB2LSB; // Standard TIFF default

    if (amrex::ParallelDescriptor::IOProcessor()) {
        if (filename.empty()) { amrex::Abort("[TiffReader::readFile] Filename cannot be empty."); }
        TiffPtr tif(TIFFOpen(filename.c_str(), "r"), TiffCloser());
        if (!tif) { amrex::Abort("[TiffReader::readFile] Failed to open TIFF file: " + filename); }

        uint32_t w32 = 0, h32 = 0; uint16_t planar = PLANARCONFIG_CONTIG;
        if (!TIFFGetField(tif.get(), TIFFTAG_IMAGEWIDTH, &w32) || !TIFFGetField(tif.get(), TIFFTAG_IMAGELENGTH, &h32)) {
            amrex::Abort("[TiffReader::readFile] Failed to get image dimensions from: " + filename);
        }
        // Use GetFieldDefaulted for tags that might be missing
        TIFFGetFieldDefaulted(tif.get(), TIFFTAG_BITSPERSAMPLE, &bps_r0);
        TIFFGetFieldDefaulted(tif.get(), TIFFTAG_SAMPLEFORMAT, &fmt_r0);
        TIFFGetFieldDefaulted(tif.get(), TIFFTAG_SAMPLESPERPIXEL, &spp_r0);
        TIFFGetFieldDefaulted(tif.get(), TIFFTAG_PLANARCONFIG, &planar);
        TIFFGetFieldDefaulted(tif.get(), TIFFTAG_FILLORDER, &fill_order_r0); // Read FillOrder, get default if missing

        width_r0 = static_cast<int>(w32); height_r0 = static_cast<int>(h32);
        bool valid_bps = (bps_r0 == 1 || bps_r0 == 8 || bps_r0 == 16 || bps_r0 == 32 || bps_r0 == 64);

        // Basic validation
        if (width_r0 <= 0 || height_r0 <= 0 || !valid_bps || planar != PLANARCONFIG_CONTIG || spp_r0 != 1) {
            std::stringstream ss;
            ss << "[TiffReader::readFile] Invalid or unsupported TIFF format in: " << filename
               << " (W=" << width_r0 << ", H=" << height_r0 << ", BPS=" << bps_r0
               << ", Planar=" << planar << ", SPP=" << spp_r0 << "). Check dimensions, BPS, PlanarConfig, SamplesPerPixel.";
            amrex::Abort(ss.str());
        }

        // Determine depth (number of directories/slices)
        depth_r0 = 0;
        if (!TIFFSetDirectory(tif.get(), 0)) { amrex::Abort("[TiffReader::readFile] Failed to set initial directory (0) in: " + filename); }
        do { depth_r0++; } while (TIFFReadDirectory(tif.get()));
        if (depth_r0 == 0) { amrex::Abort("[TiffReader::readFile] Could not read any directories (depth is zero) in: " + filename); }
    }

    // Broadcast metadata from Rank 0 to all other ranks
    int root = amrex::ParallelDescriptor::IOProcessorNumber();
    std::vector<int> idata = {width_r0, height_r0, depth_r0, static_cast<int>(bps_r0), static_cast<int>(fmt_r0), static_cast<int>(spp_r0), static_cast<int>(m_is_sequence), static_cast<int>(fill_order_r0)};
    amrex::ParallelDescriptor::Bcast(idata.data(), idata.size(), root);
    m_width = idata[0]; m_height = idata[1]; m_depth = idata[2]; m_bits_per_sample = static_cast<uint16_t>(idata[3]); m_sample_format = static_cast<uint16_t>(idata[4]); m_samples_per_pixel = static_cast<uint16_t>(idata[5]); m_is_sequence = static_cast<bool>(idata[6]); m_fill_order = static_cast<uint16_t>(idata[7]);

    // Broadcast filename
    if (amrex::ParallelDescriptor::IOProcessor()) {
        int string_len = static_cast<int>(m_filename.length());
        amrex::ParallelDescriptor::Bcast(&string_len, 1, root);
        amrex::ParallelDescriptor::Bcast(const_cast<char*>(m_filename.data()), string_len, root);
    } else {
        int string_len = 0;
        amrex::ParallelDescriptor::Bcast(&string_len, 1, root);
        m_filename.resize(string_len);
        amrex::ParallelDescriptor::Bcast(const_cast<char*>(m_filename.data()), string_len, root);
    }

    // Final check on broadcasted data
    if (m_width <= 0 || m_height <= 0 || m_depth <= 0 || m_bits_per_sample == 0) {
        amrex::Abort("TiffReader::readFile: Invalid metadata received after broadcast.");
    }

    // *** FIX: Override FillOrder for 1-bit TIFFs if needed ***
    if (m_bits_per_sample == 1) {
        if (m_fill_order != FILLORDER_LSB2MSB) { // If not already LSB
            if (amrex::ParallelDescriptor::IOProcessor()) {
                amrex::Print() << "TiffReader INFO: Detected 1-bit TIFF with missing or MSB FillOrder tag. "
                               << "Assuming LSB (2) packing for compatibility with generating script.\n";
            }
            m_fill_order = FILLORDER_LSB2MSB; // Force LSB interpretation
        }
    }
    // *** END FIX ***

    m_is_read = true;
    return true;
}


//================================================================
// readFileSequence Method (Sequence of Files)
//================================================================
bool TiffReader::readFileSequence(
    const std::string& base_pattern,
    int num_files,
    int start_index,
    int digits,
    const std::string& suffix)
{
    m_is_sequence = true; m_base_pattern = base_pattern; m_start_index = start_index; m_digits = digits; m_suffix = suffix; m_filename = "";
    // Variables local to Rank 0 for reading
    int width_r0=0, height_r0=0, depth_r0=0;
    uint16_t bps_r0=0, fmt_r0=SAMPLEFORMAT_UINT, spp_r0=1;
    uint16_t fill_order_r0 = FILLORDER_MSB2LSB; // Standard TIFF default
    std::string first_filename_r0 = "";

    if (amrex::ParallelDescriptor::IOProcessor()) {
        if (num_files <= 0 || digits <= 0 || base_pattern.empty()) {
            amrex::Abort("[TiffReader::readFileSequence] Invalid sequence parameters (num_files, digits, base_pattern).");
        }
        depth_r0 = num_files; // Depth is the number of files
        first_filename_r0 = generateFilename(base_pattern, start_index, digits, suffix);
        TiffPtr tif(TIFFOpen(first_filename_r0.c_str(), "r"), TiffCloser());
        if (!tif) { amrex::Abort("[TiffReader::readFileSequence] Failed to open first sequence file: " + first_filename_r0); }

        uint32_t w32 = 0, h32 = 0; uint16_t planar = PLANARCONFIG_CONTIG;
        if (!TIFFGetField(tif.get(), TIFFTAG_IMAGEWIDTH, &w32) || !TIFFGetField(tif.get(), TIFFTAG_IMAGELENGTH, &h32)) {
            amrex::Abort("[TiffReader::readFileSequence] Failed to get image dimensions from: " + first_filename_r0);
        }
        TIFFGetFieldDefaulted(tif.get(), TIFFTAG_BITSPERSAMPLE, &bps_r0);
        TIFFGetFieldDefaulted(tif.get(), TIFFTAG_SAMPLEFORMAT, &fmt_r0);
        TIFFGetFieldDefaulted(tif.get(), TIFFTAG_SAMPLESPERPIXEL, &spp_r0);
        TIFFGetFieldDefaulted(tif.get(), TIFFTAG_PLANARCONFIG, &planar);
        TIFFGetFieldDefaulted(tif.get(), TIFFTAG_FILLORDER, &fill_order_r0); // Read FillOrder, get default if missing

        width_r0 = static_cast<int>(w32); height_r0 = static_cast<int>(h32);
        bool valid_bps = (bps_r0 == 1 || bps_r0 == 8 || bps_r0 == 16 || bps_r0 == 32 || bps_r0 == 64);
        if (width_r0 <= 0 || height_r0 <= 0 || !valid_bps || planar != PLANARCONFIG_CONTIG || spp_r0 != 1) {
            std::stringstream ss;
             ss << "[TiffReader::readFileSequence] Invalid or unsupported TIFF format in: " << first_filename_r0
               << " (W=" << width_r0 << ", H=" << height_r0 << ", BPS=" << bps_r0
               << ", Planar=" << planar << ", SPP=" << spp_r0 << "). Check dimensions, BPS, PlanarConfig, SamplesPerPixel.";
            amrex::Abort(ss.str());
        }
        // For sequences, each file should contain only one directory
         if (TIFFReadDirectory(tif.get())) {
             amrex::Warning("[TiffReader::readFileSequence] First sequence file contains multiple directories/pages. Only the first will be used for metadata.");
         }
    }

    // Broadcast metadata from Rank 0
    int root = amrex::ParallelDescriptor::IOProcessorNumber();
    std::vector<int> idata = {width_r0, height_r0, depth_r0, static_cast<int>(bps_r0), static_cast<int>(fmt_r0), static_cast<int>(spp_r0), static_cast<int>(m_is_sequence), m_start_index, m_digits, static_cast<int>(fill_order_r0)};
    amrex::ParallelDescriptor::Bcast(idata.data(), idata.size(), root);
    m_width = idata[0]; m_height = idata[1]; m_depth = idata[2]; m_bits_per_sample = static_cast<uint16_t>(idata[3]); m_sample_format = static_cast<uint16_t>(idata[4]); m_samples_per_pixel = static_cast<uint16_t>(idata[5]); m_is_sequence = static_cast<bool>(idata[6]); m_start_index = idata[7]; m_digits = idata[8]; m_fill_order = static_cast<uint16_t>(idata[9]);

    // Broadcast sequence pattern strings
    if (amrex::ParallelDescriptor::IOProcessor()) { int string_len = static_cast<int>(m_base_pattern.length()); amrex::ParallelDescriptor::Bcast(&string_len, 1, root); amrex::ParallelDescriptor::Bcast(const_cast<char*>(m_base_pattern.data()), string_len, root); } else { int string_len = 0; amrex::ParallelDescriptor::Bcast(&string_len, 1, root); m_base_pattern.resize(string_len); amrex::ParallelDescriptor::Bcast(const_cast<char*>(m_base_pattern.data()), string_len, root); }
    if (amrex::ParallelDescriptor::IOProcessor()) { int string_len = static_cast<int>(m_suffix.length()); amrex::ParallelDescriptor::Bcast(&string_len, 1, root); amrex::ParallelDescriptor::Bcast(const_cast<char*>(m_suffix.data()), string_len, root); } else { int string_len = 0; amrex::ParallelDescriptor::Bcast(&string_len, 1, root); m_suffix.resize(string_len); amrex::ParallelDescriptor::Bcast(const_cast<char*>(m_suffix.data()), string_len, root); }

    // Final check on broadcasted data
    if (m_width <= 0 || m_height <= 0 || m_depth <= 0 || m_bits_per_sample == 0 || (m_is_sequence && m_base_pattern.empty())) {
        amrex::Abort("TiffReader::readFileSequence: Invalid metadata received after broadcast.");
    }

    // *** FIX: Override FillOrder for 1-bit TIFFs if needed ***
    if (m_bits_per_sample == 1) {
        if (m_fill_order != FILLORDER_LSB2MSB) { // If not already LSB
            if (amrex::ParallelDescriptor::IOProcessor()) {
                amrex::Print() << "TiffReader INFO: Detected 1-bit TIFF sequence. Overriding FillOrder from MSB (1) or other ("
                               << m_fill_order << ") to LSB (2) for compatibility with generating script.\n";
            }
            m_fill_order = FILLORDER_LSB2MSB; // Force LSB interpretation
        }
    }
    // *** END FIX ***

    m_is_read = true;
    return true;
}


//================================================================
// readDistributedIntoFab Method - Main Data Reading Logic
//================================================================
void TiffReader::readDistributedIntoFab(
    amrex::iMultiFab& dest_mf,
    int value_if_true,
    int value_if_false,
    double raw_threshold
) const
{
    if (!m_is_read) {
        amrex::Abort("[TiffReader::readDistributedIntoFab] Cannot read, metadata not processed successfully.");
    }

    // Assertions
    AMREX_ALWAYS_ASSERT_WITH_MESSAGE(dest_mf.boxArray().minimalBox() == this->box(),
                                     "TiffReader::readDistributedIntoFab: Destination MultiFab BoxArray domain does not match reader Box.");
    AMREX_ALWAYS_ASSERT_WITH_MESSAGE(dest_mf.nComp() == 1,
                                     "TiffReader::readDistributedIntoFab: Destination MultiFab must have exactly 1 component.");
    AMREX_ALWAYS_ASSERT_WITH_MESSAGE(dest_mf.nGrow() == 0,
                                     "TiffReader::readDistributedIntoFab: Destination MultiFab must have 0 ghost cells.");

    const int bits_per_sample_val = m_bits_per_sample;
    const size_t bytes_per_sample = (bits_per_sample_val >= 8) ? (bits_per_sample_val / 8) : 1; // Treat BPS=1 as needing 1 byte conceptually for pixel processing
    const size_t bytes_per_pixel = bytes_per_sample * m_samples_per_pixel; // Assumes SPP=1 based on metadata checks

    if (bits_per_sample_val == 0 ) {
        amrex::Abort("[TiffReader::readDistributedIntoFab] Bits per sample is zero!");
    }

    // --- TIFF Handle Management ---
    // For stack files, open one shared handle (read-only access should be okay if protected)
    // For sequence files, each thread will open its own handle as needed
    TIFF* shared_tif_stack_raw_ptr = nullptr;
    TiffPtr shared_tif_stack_handle = nullptr; // Manages lifetime if stack file
    if (!m_is_sequence) {
        // Only IO Processor opens initially, pointer shared conceptually
        // NOTE: Direct concurrent reads on same handle might require care / OMP critical
        if (amrex::ParallelDescriptor::IOProcessor()) {
             shared_tif_stack_handle = TiffPtr(TIFFOpen(m_filename.c_str(), "r"), TiffCloser());
             if (!shared_tif_stack_handle) {
                 amrex::Abort("[TiffReader::readDistributedIntoFab] FATAL: Rank 0 failed to open shared TIFF file: " + m_filename);
             }
             shared_tif_stack_raw_ptr = shared_tif_stack_handle.get(); // Get raw pointer
        }
         // Broadcast the raw pointer address (handle) - This is potentially unsafe if ranks try to use it concurrently without locks!
         // A better approach might be for each rank/thread to open its own handle if concurrent reads are needed without locks.
         // Sticking with the locked approach for now.
         // amrex::ParallelDescriptor::Bcast(&shared_tif_stack_raw_ptr, sizeof(TIFF*), amrex::ParallelDescriptor::IOProcessorNumber());
         // --> Let's stick to OMP critical sections around TIFF reads instead of broadcasting handle.

    } // End stack handle setup

    // Store overall image dimensions locally for boundary checks inside loop
    const int image_width = m_width;
    const int image_height = m_height;
    const int image_depth = m_depth;
    const uint16_t fill_order_local = m_fill_order; // Local copy for loop

#ifdef AMREX_USE_OMP
#pragma omp parallel if (amrex::Gpu::notInLaunchRegion())
#endif
    {
        // Thread-local buffer for reading strips/tiles
        std::vector<unsigned char> temp_buffer;
        // Thread-local handle for sequence files
        TiffPtr sequence_tif_handle = nullptr;
        TIFF* current_tif_raw_ptr = nullptr; // Pointer to use (either shared or sequence)

        for (amrex::MFIter mfi(dest_mf, amrex::TilingIfNotGPU()); mfi.isValid(); ++mfi)
        {
            amrex::Array4<int> fab_arr = dest_mf.array(mfi);
            const amrex::Box& tile_box = mfi.tilebox(); // Use tilebox for OMP tiling

            const int k_min = tile_box.smallEnd(2);
            const int k_max = tile_box.bigEnd(2);

            // Loop through Z slices relevant to this Fab/Tile
            for (int k = k_min; k <= k_max; ++k) {

                if (m_is_sequence) {
                    // --- Sequence Reading Logic ---
                    std::string current_filename = generateFilename(m_base_pattern, m_start_index + k, m_digits, m_suffix);
                    sequence_tif_handle = TiffPtr(TIFFOpen(current_filename.c_str(), "r"), TiffCloser());
                    if (!sequence_tif_handle) { amrex::Abort("[TiffReader] Failed to open sequence file: " + current_filename); }
                    current_tif_raw_ptr = sequence_tif_handle.get();
                    // No need for OMP critical section here as each thread opens its own file
                } else {
                    // --- Stack Reading Logic ---
                    // Use the shared handle pointer (will be protected by critical section)
                    // We don't assign here, will use shared_tif_stack_raw_ptr inside lock
                     current_tif_raw_ptr = shared_tif_stack_raw_ptr; // This ptr itself isn't used, the shared one is
                }

                // Determine if the current Z-slice (directory k) uses tiles or strips
                bool is_tiled = false;
                #pragma omp critical (TiffReadLock) // Protect shared handle access
                {
                    TIFF* tif_handle = m_is_sequence ? current_tif_raw_ptr : shared_tif_stack_raw_ptr;
                    if (!tif_handle) { amrex::Abort("[TiffReader] FATAL: TIFF Handle is NULL before reading!"); }
                     if (!m_is_sequence) { // Need to set directory for stack files
                         if (!TIFFSetDirectory(tif_handle, static_cast<tdir_t>(k))) { std::string error_msg = "[TiffReader] FATAL: Failed to set directory " + std::to_string(k) + " in file: " + m_filename; amrex::Abort(error_msg.c_str()); }
                     }
                     is_tiled = TIFFIsTiled(tif_handle);
                } // End critical section for checking tiled


                if (is_tiled) {
                    // --- Tiled Reading ---
                    uint32_t tile_width = 0, tile_height = 0;
                    tsize_t tile_buffer_size = 0;
                    #pragma omp critical (TiffReadLock)
                    {
                        TIFF* tif_handle = m_is_sequence ? current_tif_raw_ptr : shared_tif_stack_raw_ptr;
                        TIFFGetField(tif_handle, TIFFTAG_TILEWIDTH, &tile_width);
                        TIFFGetField(tif_handle, TIFFTAG_TILELENGTH, &tile_height);
                        tile_buffer_size = TIFFTileSize(tif_handle);
                    } // End critical section

                    if (tile_width == 0 || tile_height == 0) { amrex::Abort("[TiffReader] FATAL: Invalid tile dimensions."); }
                    if (tile_buffer_size <= 0) { amrex::Abort("[TiffReader] FATAL: Invalid tile buffer size."); }
                    if (temp_buffer.size() < static_cast<size_t>(tile_buffer_size)) { temp_buffer.resize(tile_buffer_size); }

                    const int chunk_width = static_cast<int>(tile_width); // Use for indexing calculations
                    int tx_min = tile_box.smallEnd(0) / tile_width;
                    int tx_max = tile_box.bigEnd(0) / tile_width;
                    int ty_min = tile_box.smallEnd(1) / tile_height;
                    int ty_max = tile_box.bigEnd(1) / tile_height;

                    for (int ty = ty_min; ty <= ty_max; ++ty) {
                        for (int tx = tx_min; tx <= tx_max; ++tx) {
                            int chunk_origin_x = tx * tile_width;
                            int chunk_origin_y = ty * tile_height;
                            amrex::Box chunk_abs_box(amrex::IntVect(chunk_origin_x, chunk_origin_y, k),
                                                     amrex::IntVect(chunk_origin_x + tile_width - 1, chunk_origin_y + tile_height - 1, k));
                            amrex::Box intersection = tile_box & chunk_abs_box;

                            if (intersection.ok()) {
                                tsize_t bytes_read = -1;
                                #pragma omp critical (TiffReadLock)
                                {
                                    TIFF* tif_handle = m_is_sequence ? current_tif_raw_ptr : shared_tif_stack_raw_ptr;
                                     // Ensure directory is still correct for stack files inside lock
                                     if (!m_is_sequence && (TIFFCurrentDirectory(tif_handle) != static_cast<tdir_t>(k))) {
                                         if (!TIFFSetDirectory(tif_handle, static_cast<tdir_t>(k))) { amrex::Abort("[TiffReader] FATAL: Failed to re-set directory in tile loop."); }
                                     }
                                    ttile_t tile_index = TIFFComputeTile(tif_handle, chunk_origin_x, chunk_origin_y, 0, 0);
                                    bytes_read = TIFFReadEncodedTile(tif_handle, tile_index, temp_buffer.data(), tile_buffer_size);
                                } // End critical section

                                if (bytes_read < 0) { std::string error_msg = "[TiffReader] FATAL: Error reading tile index " + std::to_string(TIFFComputeTile(m_is_sequence ? current_tif_raw_ptr : shared_tif_stack_raw_ptr, chunk_origin_x, chunk_origin_y, 0, 0)) + " slice " + std::to_string(k); amrex::Abort(error_msg.c_str()); }

                                // Process data (using thread-local buffer)
                                amrex::LoopOnCpu(intersection, [&](int i, int j, int k_loop ) {
                                    // ... [Identical Voxel Processing Logic as below in Striped section] ...
                                    double value_as_double = 0.0; int bit_value = -1; unsigned char packed_byte = 0; size_t byte_index_in_buffer = 0; int bit_index_in_byte = 0; size_t linear_pixel_index_in_chunk = 0;
                                    if (bits_per_sample_val == 1) {
                                         int i_in_chunk = i - chunk_origin_x; int j_in_chunk = j - chunk_origin_y; linear_pixel_index_in_chunk = static_cast<size_t>(j_in_chunk) * chunk_width + i_in_chunk; byte_index_in_buffer = linear_pixel_index_in_chunk / 8; bit_index_in_byte = linear_pixel_index_in_chunk % 8;
                                         if (byte_index_in_buffer < static_cast<size_t>(bytes_read)) { packed_byte = temp_buffer[byte_index_in_buffer]; bit_value = (fill_order_local == FILLORDER_MSB2LSB) ? (packed_byte >> (7 - bit_index_in_byte)) & 1 : (packed_byte >> bit_index_in_byte) & 1; value_as_double = static_cast<double>(bit_value); } else { value_as_double = 0.0; bit_value = -2; }
                                    } else { int i_in_chunk = i - chunk_origin_x; int j_in_chunk = j - chunk_origin_y; size_t offset_in_buffer = (static_cast<size_t>(j_in_chunk) * chunk_width + i_in_chunk) * bytes_per_pixel; if (offset_in_buffer + bytes_per_sample <= static_cast<size_t>(bytes_read)) { const unsigned char* src_ptr = temp_buffer.data() + offset_in_buffer; value_as_double = interpretBytesAsDouble(src_ptr, bits_per_sample_val, m_sample_format); } else { value_as_double = 0.0; } }
                                    // *** Debug Block ***
                                     if (amrex::Verbose() >= 3 && amrex::ParallelDescriptor::IOProcessor()) { bool is_boundary = ( i == image_width - 1 || j == image_height - 1 || k_loop == image_depth - 1 || i == 0 || j == 0 || k_loop == 0 ); if (is_boundary && bits_per_sample_val == 1) { amrex::Print().SetPrecision(0) << "TIFF_DBG(Tile): Voxel(" << i << "," << j << "," << k_loop << ") Tile(" << tx << "," << ty << ") ChunkIdx(" << linear_pixel_index_in_chunk << ") ByteIdx(" << byte_index_in_buffer << ") BitInByte(" << bit_index_in_byte << ") PackedByte(0x" << std::hex << static_cast<int>(packed_byte) << std::dec << ") RawBitValue(" << bit_value << ") Thresholded(" << ((value_as_double > raw_threshold) ? value_if_true : value_if_false) << ")\n"; } }
                                    // *** End Debug Block ***
                                    fab_arr(i, j, k_loop) = (value_as_double > raw_threshold) ? value_if_true : value_if_false;
                                }); // End LoopOnCpu
                            } // end if intersection ok
                        } // end tx loop
                    } // end ty loop
                } else { // Not Tiled -> Striped Reading
                    // --- Striped Reading ---
                    uint32_t rows_per_strip = 0; uint32_t current_height32 = static_cast<uint32_t>(m_height);
                    tsize_t strip_buffer_size = 0;
                    #pragma omp critical (TiffReadLock)
                    {
                        TIFF* tif_handle = m_is_sequence ? current_tif_raw_ptr : shared_tif_stack_raw_ptr;
                         // Ensure directory is still correct for stack files inside lock
                         if (!m_is_sequence && (TIFFCurrentDirectory(tif_handle) != static_cast<tdir_t>(k))) {
                             if (!TIFFSetDirectory(tif_handle, static_cast<tdir_t>(k))) { amrex::Abort("[TiffReader] FATAL: Failed to re-set directory in strip loop."); }
                         }
                        TIFFGetFieldDefaulted(tif_handle, TIFFTAG_ROWSPERSTRIP, &rows_per_strip);
                        strip_buffer_size = TIFFStripSize(tif_handle);
                    } // End critical section

                    if (rows_per_strip == 0 || rows_per_strip > current_height32) { rows_per_strip = current_height32; } // Handle default/invalid RPS
                    if (strip_buffer_size <= 0) { amrex::Abort("[TiffReader] FATAL: Invalid strip buffer size."); }
                    if (temp_buffer.size() < static_cast<size_t>(strip_buffer_size)) { temp_buffer.resize(strip_buffer_size); }

                    const int chunk_width = m_width; // For strips, chunk width is image width
                    int strip_y_min = tile_box.smallEnd(1);
                    int strip_y_max = tile_box.bigEnd(1);
                    tstrip_t first_strip = TIFFComputeStrip(m_is_sequence ? current_tif_raw_ptr : shared_tif_stack_raw_ptr, strip_y_min, 0);
                    tstrip_t last_strip = TIFFComputeStrip(m_is_sequence ? current_tif_raw_ptr : shared_tif_stack_raw_ptr, strip_y_max, 0);

                    for (tstrip_t strip = first_strip; strip <= last_strip; ++strip) {
                        uint32_t strip_origin_y_uint = strip * rows_per_strip;
                        if (strip_origin_y_uint > std::numeric_limits<int>::max()) { amrex::Abort("Strip origin Y exceeds integer limits"); }
                        int chunk_origin_y = static_cast<int>(strip_origin_y_uint);
                        const int chunk_origin_x = 0; // Strips start at x=0

                        // Calculate actual rows in this specific strip (can be less than rows_per_strip for the last one)
                        uint32_t strip_rows_this = std::min(rows_per_strip, current_height32 - strip_origin_y_uint);
                        if (strip_rows_this == 0) continue; // Should not happen if loop bounds are correct
                        int chunk_height = static_cast<int>(strip_rows_this);

                        amrex::Box chunk_abs_box(amrex::IntVect(chunk_origin_x, chunk_origin_y, k),
                                                 amrex::IntVect(chunk_origin_x + chunk_width - 1, chunk_origin_y + chunk_height - 1, k));
                        amrex::Box intersection = tile_box & chunk_abs_box;

                        if (intersection.ok()) {
                            tsize_t bytes_read = -1;
                            #pragma omp critical (TiffReadLock)
                            {
                                TIFF* tif_handle = m_is_sequence ? current_tif_raw_ptr : shared_tif_stack_raw_ptr;
                                 // Ensure directory is still correct for stack files inside lock
                                 if (!m_is_sequence && (TIFFCurrentDirectory(tif_handle) != static_cast<tdir_t>(k))) {
                                     if (!TIFFSetDirectory(tif_handle, static_cast<tdir_t>(k))) { amrex::Abort("[TiffReader] FATAL: Failed to re-set directory in strip loop."); }
                                 }
                                bytes_read = TIFFReadEncodedStrip(tif_handle, strip, temp_buffer.data(), strip_buffer_size);
                            } // End critical section

                            if (bytes_read < 0) { std::string error_msg = "[TiffReader] FATAL: Error reading strip " + std::to_string(strip) + " slice " + std::to_string(k); amrex::Abort(error_msg.c_str()); }

                            // Process data (using thread-local buffer)
                            amrex::LoopOnCpu(intersection, [&](int i, int j, int k_loop ) {
                                double value_as_double = 0.0;
                                int bit_value = -1; // Initialize to invalid
                                unsigned char packed_byte = 0;
                                size_t byte_index_in_buffer = 0;
                                int bit_index_in_byte = 0;
                                size_t linear_pixel_index_in_chunk = 0;

                                if (bits_per_sample_val == 1) {
                                    int i_in_chunk = i - chunk_origin_x; // i_in_chunk is just i
                                    int j_in_chunk = j - chunk_origin_y; // j relative to start of strip
                                    linear_pixel_index_in_chunk = static_cast<size_t>(j_in_chunk) * chunk_width + i_in_chunk;
                                    byte_index_in_buffer = linear_pixel_index_in_chunk / 8;
                                    bit_index_in_byte = linear_pixel_index_in_chunk % 8;
                                    if (byte_index_in_buffer < static_cast<size_t>(bytes_read)) {
                                        packed_byte = temp_buffer[byte_index_in_buffer];
                                        bit_value = (fill_order_local == FILLORDER_MSB2LSB) ? (packed_byte >> (7 - bit_index_in_byte)) & 1 : (packed_byte >> bit_index_in_byte) & 1;
                                        value_as_double = static_cast<double>(bit_value);
                                    } else { value_as_double = 0.0; bit_value = -2; /* Indicate Bounds Error */ }
                                } else { // BPS >= 8 logic
                                    int i_in_chunk = i - chunk_origin_x;
                                    int j_in_chunk = j - chunk_origin_y;
                                    size_t offset_in_buffer = (static_cast<size_t>(j_in_chunk) * chunk_width + i_in_chunk) * bytes_per_pixel;
                                    if (offset_in_buffer + bytes_per_sample <= static_cast<size_t>(bytes_read)) {
                                        const unsigned char* src_ptr = temp_buffer.data() + offset_in_buffer;
                                        value_as_double = interpretBytesAsDouble(src_ptr, bits_per_sample_val, m_sample_format);
                                    } else { value_as_double = 0.0; }
                                }

                                // *** Debug Block ***
                                if (amrex::Verbose() >= 3 && amrex::ParallelDescriptor::IOProcessor()) {
                                     // Check all boundaries now for debug print
                                    bool is_boundary = ( i == image_width - 1 || j == image_height - 1 || k_loop == image_depth - 1 || i == 0 || j == 0 || k_loop == 0 );
                                    if (is_boundary && bits_per_sample_val == 1) {
                                        amrex::Print().SetPrecision(0) << "TIFF_DBG(Strip): Voxel(" << i << "," << j << "," << k_loop << ") Strip(" << strip << ") ChunkIdx(" << linear_pixel_index_in_chunk << ") ByteIdx(" << byte_index_in_buffer << ") BitInByte(" << bit_index_in_byte << ") PackedByte(0x" << std::hex << static_cast<int>(packed_byte) << std::dec << ") RawBitValue(" << bit_value << ") Thresholded(" << ((value_as_double > raw_threshold) ? value_if_true : value_if_false) << ")\n";
                                        // Add flush if needed, but let's see if print itself works first
                                        // amrex::OutStream() << std::flush;
                                    }
                                }
                                // *** End Debug Block ***

                                fab_arr(i, j, k_loop) = (value_as_double > raw_threshold) ? value_if_true : value_if_false;
                            }); // End LoopOnCpu
                        } // end if intersection ok
                    } // end strip loop
                } // end if tiled/striped
            } // End loop k (Z-slices)
        } // End MFIter loop
    } // End OMP parallel region

    amrex::ParallelDescriptor::Barrier("TiffReader::readDistributedIntoFab");
}

//================================================================
// Public threshold methods (call the main implementation)
//================================================================
void TiffReader::threshold(double raw_threshold, int value_if_true, int value_if_false, amrex::iMultiFab& mf) const
{
    // Calls the main implementation above
    readDistributedIntoFab(mf, value_if_true, value_if_false, raw_threshold);
}

void TiffReader::threshold(double raw_threshold, amrex::iMultiFab& mf) const {
    // Calls the overload with default true/false values (1=True, 0=False)
    threshold(raw_threshold, 1, 0, mf);
}

} // namespace OpenImpala
