# .github/workflows/build-test.yml
name: Build and Test OpenImpala Makefile (Singularity Cache)

on:
  push:
    # Trigger on pushes to these specific branches
    branches:
      - main
      - working
      - build
      - makefile # <-- Added makefile branch trigger
  pull_request:
    # Trigger on Pull Requests targeting main branch
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering

jobs:
  # Job 1: Build dependencies and cache them in a sandbox
  cache-dependencies:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key-step.outputs.key }} # Output the key used

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.2.5 # Use consistent version

      - name: Generate Cache Key
        id: cache-key-step
        # Key based on hash of the dependency recipe file + runner OS + date
        run: |
          RECIPE_FILE="containers/Singularity.deps.def"
          CACHE_DATE=$(date +'%Y-%m') # Add month to key to allow periodic refresh
          # Use literal path string for hashFiles
          echo "key=deps-cache-${{ runner.os }}-${CACHE_DATE}-$(echo -n ${{ hashFiles('containers/Singularity.deps.def') }} | md5sum | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT

      - name: Cache Dependencies Sandbox
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ./dependency_sandbox # Directory to cache
          key: ${{ steps.cache-key-step.outputs.key }}
          # restore-keys: | # Optional: allow restoring slightly older caches
          #   deps-cache-${{ runner.os }}-

      - name: Build Dependencies Sandbox (if cache miss)
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          RECIPE_FILE="containers/Singularity.deps.def"
          if [ ! -f "$RECIPE_FILE" ]; then
            echo "Error: Dependency recipe file $RECIPE_FILE not found!"
            exit 1
          fi
          echo "Building dependencies sandbox from $RECIPE_FILE..."
          # Build into a sandbox directory (folder)
          apptainer build --fakeroot --sandbox ./dependency_sandbox "$RECIPE_FILE"

  # Job 2: Build OpenImpala using the cached dependencies
  build-openimpala:
    needs: cache-dependencies # Run after dependencies are cached/restored
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.2.5 # Use consistent version

      - name: Restore Dependencies Sandbox
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ./dependency_sandbox
          # Use the exact key generated by the first job
          key: ${{ needs.cache-dependencies.outputs.cache-key }}

      - name: Check if sandbox exists
        run: |
          if [ ! -d "./dependency_sandbox" ]; then
            echo "Error: Dependency sandbox not found after restore. Dependency build likely failed."
            exit 1
          fi
          echo "Dependency sandbox restored successfully."

      - name: Build OpenImpala using Cached Dependencies
        run: |
          echo "Building OpenImpala inside sandbox environment..."
          # Execute 'make' inside the sandbox environment
          # Mount the current checkout directory (containing the Makefile) into /opt/openImpala
          # The sandbox itself contains /usr/local, /opt/hdf5, /opt/amrex etc.
          apptainer exec --bind $PWD:/opt/openImpala \
            ./dependency_sandbox \
            bash -c 'cd /opt/openImpala && make clean && make -j$(nproc)'
          # Check make exit status
          if [ $? -ne 0 ]; then
            echo "Error: OpenImpala make failed."
            exit 1
          fi
          echo "OpenImpala built successfully."

      # Optional: Add steps here to run tests using the sandbox
      # - name: Run Tests
      #   run: |
      #     apptainer exec --bind $PWD:/opt/openImpala \
      #       ./dependency_sandbox \
      #       bash -c 'cd /opt/openImpala/build/tests && ./tSomeTest'
