# .github/workflows/build-test.yml
name: Build and Test OpenImpala Makefile (Singularity Cache + Debug)

on:
  push:
    # Trigger on pushes to these specific branches
    branches:
      - main
      - working
      - build
      - 'makefile' # Include makefile branch trigger
  pull_request:
    # Trigger on Pull Requests targeting main branch
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering

jobs:
  # Job 1: Build dependencies and cache them in a SIF image
  cache-dependencies:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key-step.outputs.key }} # Output the key used

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.2.5 # Use consistent version

      - name: Generate Cache Key
        id: cache-key-step
        # Key based on hash of the dependency recipe file + runner OS + date
        run: |
          RECIPE_FILE="containers/Singularity.deps.def"
          CACHE_DATE=$(date +'%Y-%m') # Add month to key to allow periodic refresh
          # Use literal path string for hashFiles and indicate SIF cache
          echo "key=deps-sif-cache-${{ runner.os }}-${CACHE_DATE}-$(echo -n ${{ hashFiles('containers/Singularity.deps.def') }} | md5sum | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT

      - name: Cache Dependency SIF Image
        id: cache-deps
        uses: actions/cache@v4
        with:
          # Cache the single SIF file
          path: dependency_image.sif
          key: ${{ steps.cache-key-step.outputs.key }}
          # restore-keys: | # Optional: allow restoring slightly older caches
          #    deps-sif-cache-${{ runner.os }}-

      - name: Build Dependency SIF Image (if cache miss)
        # This step runs only if the SIF file wasn't found in the cache
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          RECIPE_FILE="containers/Singularity.deps.def"
          TARGET_SIF="dependency_image.sif"
          if [ ! -f "$RECIPE_FILE" ]; then
            echo "Error: Dependency recipe file $RECIPE_FILE not found!"
            exit 1
          fi
          echo "Building dependencies SIF image '$TARGET_SIF' from $RECIPE_FILE..."
          # Build the SIF file directly using sudo
          sudo apptainer build "$TARGET_SIF" "$RECIPE_FILE"
          # Check build exit status IMMEDIATELY
          if [ $? -ne 0 ]; then
              echo "Error: Apptainer SIF build failed."
              exit 1 # Exit if build failed
          fi
          echo "Apptainer SIF build successful."
      # No chown needed for single SIF file caching

  # Job 2: Build OpenImpala using the cached dependency SIF
  build-openimpala:
    needs: cache-dependencies # Run after dependencies are cached/restored
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.2.5 # Use consistent version

      - name: Restore Dependency SIF Image
        id: cache-deps
        uses: actions/cache@v4
        with:
          # Restore the single SIF file
          path: dependency_image.sif
          # Use the exact key generated by the first job
          key: ${{ needs.cache-dependencies.outputs.cache-key }}
          # Fail job if cache cannot be restored (indicates dependency build failed)
          fail-on-cache-miss: true

      - name: Check if Dependency SIF exists
        run: |
          if [ ! -f "./dependency_image.sif" ]; then
            echo "Error: Dependency SIF image not found after cache restore."
            exit 1
          fi
          echo "Dependency SIF image restored successfully."
          ls -lh ./dependency_image.sif # Show file info

      - name: Build OpenImpala using Dependency SIF (with make debug)
        id: make_build # Give step an id
        continue-on-error: true # Allow step to fail so logs can be uploaded
        run: |
          # --- START DEBUG STEP ---
          echo "DEBUG: Printing environment inside container..."
          # Use brackets to clearly show start/end of variable values
          sudo apptainer exec --bind $PWD:/src ./dependency_image.sif bash -c 'echo "DEBUG AMREX_HOME=[$AMREX_HOME]"; echo "DEBUG HYPRE_HOME=[$HYPRE_HOME]"; echo "DEBUG HDF5_HOME=[$HDF5_HOME]"; echo "DEBUG H5CPP_HOME=[$H5CPP_HOME]"; echo "DEBUG TIFF_HOME=[$TIFF_HOME]"'
          echo "DEBUG: Environment print finished."
          # --- END DEBUG STEP ---

          echo "Building OpenImpala using SIF image environment (with make debug)..."
          # Execute 'make clean' first
          sudo apptainer exec --bind $PWD:/src \
            ./dependency_image.sif \
            bash -c 'cd /src && make clean'
          # Execute 'make -d', redirecting all output to log file
          echo "Running make -d to capture debug output..."
          sudo apptainer exec --bind $PWD:/src \
            ./dependency_image.sif \
            bash -c 'cd /src && make -d -j$(nproc)' > make_debug_output.log 2>&1
          # Capture the exit code of make -d
          MAKE_EXIT_CODE=$?
          echo "Make exit code: $MAKE_EXIT_CODE"
          # Explicitly fail the step if make failed
          if [ $MAKE_EXIT_CODE -ne 0 ]; then exit $MAKE_EXIT_CODE; fi
          echo "OpenImpala build command finished (check logs)."

      - name: Upload Make Debug Log
        # Run this step always after the make attempt to capture log on success or failure
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: make-debug-log-${{ github.run_id }} # Unique artifact name per run
          path: make_debug_output.log # Path to the log file generated above
          retention-days: 5 # Keep logs for 5 days

      # Explicitly fail the overall job if the 'make_build' step failed
      - name: Fail job if make failed
        if: steps.make_build.outcome == 'failure'
        run: |
          echo "Make command failed. See uploaded 'make-debug-log' artifact for details."
          exit 1

      # Optional: Add steps here to run tests using the SIF image IF make succeeded
      # - name: Run Tests (if build succeeded)
      #   if: steps.make_build.outcome == 'success'
      #   run: |
      #     sudo apptainer exec --bind $PWD:/src \
      #        ./dependency_image.sif \
      #        bash -c 'cd /src/build/tests && ./tSomeTest'
