name: Build and Release Singularity Container

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.2.5

      - name: Restore Dependency SIF Cache
        id: cache-restore-sif
        uses: actions/cache/restore@v4
        with:
          path: dependency_image.sif
          key: ${{ runner.os }}-apptainer-sif-${{ hashFiles('containers/Singularity.deps.def') }}

      - name: Build Dependency SIF (if cache miss)
        if: steps.cache-restore-sif.outputs.cache-hit != 'true'
        run: |
          echo "Cache miss. Building dependency_image.sif..."
          sudo apptainer build --force dependency_image.sif containers/Singularity.deps.def

      - name: Save Dependency SIF to Cache
        if: steps.cache-restore-sif.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: dependency_image.sif
          key: ${{ steps.cache-restore-sif.outputs.cache-primary-key || format('{0}-apptainer-sif-{1}', runner.os, hashFiles('containers/Singularity.deps.def')) }}

      - name: Compile Application Binaries
        run: |
          echo "Compiling application executables inside the dependency container..."
          sudo apptainer exec \
            --bind $PWD:/src \
            ./dependency_image.sif \
            bash -c 'source /opt/rh/gcc-toolset-11/enable && cd /src && make all -j$(nproc)'
          echo "Compilation complete."

      - name: Build Final Release SIF
        run: |
          echo "Building the final, clean application container for release..."
          SIF_FILENAME="openimpala-${{ github.ref_name }}.sif"
          STAGING_DIR=$(mktemp -d)
          echo "Using staging directory: $STAGING_DIR"

          echo "Copying compiled application binaries and custom libraries to staging area..."
          cp -r ./build/apps "$STAGING_DIR/"
          
          # FIX: Be specific about what to copy from the build container.
          # We only want our custom-compiled libraries (amrex, hypre, etc.), NOT the entire
          # gcc-toolset-11 from the builder. The runtime toolset will be installed by dnf.
          sudo apptainer exec \
            --bind "$STAGING_DIR:/staging" \
            ./dependency_image.sif \
            bash -c 'tar -chf - /usr/local /opt/amrex /opt/hypre /opt/hdf5 /opt/libtiff | (cd /staging && tar xf -)'
            
          echo "Creating final Singularity definition file..."
          cat > Singularity.final.def <<-EOF
          Bootstrap: docker
          From: quay.io/rockylinux/rockylinux:8

          %files
              # Copy our custom-built application and libraries from the staging area
              "$STAGING_DIR/apps" /usr/bin/
              "$STAGING_DIR/opt" /
              "$STAGING_DIR/usr/local" /usr/

          %post
              # Install the essential RUNTIME dependencies for our custom libraries
              dnf install -y \
                  gcc-toolset-11-runtime \
                  hwloc-libs \
                  libevent \
                  libjpeg-turbo \
                  libibverbs && \
              dnf clean all -y
              
              # Create linker cache config files for custom library locations
              echo "/usr/local/lib" > /etc/ld.so.conf.d/usrlocal.conf
              echo "/opt/amrex/25.03/lib" > /etc/ld.so.conf.d/amrex.conf
              echo "/opt/hypre/v2.32.0/lib" > /etc/ld.so.conf.d/hypre.conf
              echo "/opt/hdf5/1.12.3/lib" > /etc/ld.so.conf.d/hdf5.conf
              echo "/opt/libtiff/4.6.0/lib" > /etc/ld.so.conf.d/libtiff.conf

              # Update the system linker cache
              ldconfig

          %environment
              source /opt/rh/gcc-toolset-11/enable
              export LC_ALL=C
          EOF

          echo "Building final SIF..."
          sudo apptainer build "$SIF_FILENAME" Singularity.final.def
          echo "SIF_FILENAME=$SIF_FILENAME" >> $GITHUB_ENV
          
      - name: Create GitHub Release and Upload SIF
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.SIF_FILENAME }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
