name: Build and Release Singularity Container

on:
  push:
    # This is the important part: only trigger on tags that look like versions.
    tags:
      - 'v*'
  workflow_dispatch: # Allows manual trigger via Actions tab

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.2.5

      - name: Build Apptainer containers
        run: |
          # Step 1: Build the dependency container.
          echo "Building dependency container..."
          sudo apptainer build dependency_image.sif containers/Singularity.deps.def

          # Step 2: Build the final application container.
          echo "Building application container..."
          # github.ref_name will be the tag name, e.g., "v1.1.0"
          SIF_FILENAME="openimpala-${{ github.ref_name }}.sif"
          sudo apptainer build "$SIF_FILENAME" containers/Singularity.def

          echo "SIF_FILENAME=$SIF_FILENAME" >> $GITHUB_ENV

      - name: Create GitHub Release and Upload SIF Asset
        # This condition ensures the release step ONLY runs when a tag is pushed.
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.SIF_FILENAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Build Output
        run: |
          echo "Checking existence and size of ${{ env.SIF_FILENAME }}"
          ls -lh "${{ env.SIF_FILENAME }}"
          if [ ! -s "${{ env.SIF_FILENAME }}" ]; then
            echo "Error: Built SIF file is missing or empty."
            exit 1
          fi
          echo "Build verification step passed."
