name: Build and Release Singularity Container

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ... (setup-apptainer, cache steps are unchanged) ...
      - name: Set up Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.2.5

      - name: Restore Dependency SIF Cache
        id: cache-restore-sif
        uses: actions/cache/restore@v4
        with:
          path: dependency_image.sif
          key: ${{ runner.os }}-apptainer-sif-${{ hashFiles('containers/Singularity.deps.def') }}

      - name: Build Dependency SIF (if cache miss)
        if: steps.cache-restore-sif.outputs.cache-hit != 'true'
        run: |
          echo "Cache miss. Building dependency_image.sif..."
          sudo apptainer build --force dependency_image.sif containers/Singularity.deps.def

      - name: Save Dependency SIF to Cache
        if: steps.cache-restore-sif.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: dependency_image.sif
          key: ${{ steps.cache-restore-sif.outputs.cache-primary-key || format('{0}-apptainer-sif-{1}', runner.os, hashFiles('containers/Singularity.deps.def')) }}

      - name: Compile Application Binaries
        run: |
          echo "Compiling application executables inside the dependency container..."
          sudo apptainer exec \
            --bind $PWD:/src \
            ./dependency_image.sif \
            bash -c 'source /opt/rh/gcc-toolset-11/enable && cd /src && make all -j$(nproc)'
          echo "Compilation complete."

      - name: Build Final Release SIF
        run: |
          echo "Building the final, clean application container for release..."
          SIF_FILENAME="openimpala-${{ github.ref_name }}.sif"
          STAGING_DIR=$(mktemp -d)
          echo "Using staging directory: $STAGING_DIR"

          echo "Copying compiled application binaries and custom libraries to staging area..."
          cp -r ./build/apps "$STAGING_DIR/"
          sudo apptainer exec \
            --bind "$STAGING_DIR:/staging" \
            ./dependency_image.sif \
            bash -c 'tar -chf - /usr/local /opt/amrex /opt/hypre /opt/hdf5 /opt/libtiff | (cd /staging && tar xf -)'
            
          echo "Creating final Singularity definition file..."
          cat > Singularity.final.def <<-EOF
          Bootstrap: docker
          From: quay.io/rockylinux/rockylinux:8

          %files
              "$STAGING_DIR/apps" /usr/bin/
              "$STAGING_DIR/opt" /
              "$STAGING_DIR/usr/local" /usr/

          %post
              # --- THIS IS THE FINAL FIX BASED ON OFFICIAL DOCUMENTATION ---
              # We now install the CORRECT package that provides the gfortran
              # compiler and, crucially, its runtime libraries like libgfortran.so.5.
              dnf install -y \
                  gcc-toolset-11-gcc-gfortran \
                  hwloc-libs \
                  libevent \
                  libjpeg-turbo \
                  libibverbs && \
              dnf clean all -y

          %environment
              # The environment script is needed to put the libraries on the PATH
              source /opt/rh/gcc-toolset-11/enable
              export LC_ALL=C
          EOF

          echo "Building final SIF..."
          sudo apptainer build "$SIF_FILENAME" Singularity.final.def
          echo "SIF_FILENAME=$SIF_FILENAME" >> $GITHUB_ENV
          
      - name: Create GitHub Release and Upload SIF
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.SIF_FILENAME }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
