name: Build and Release Singularity Container

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.2.5

      - name: Restore Dependency SIF Cache
        id: cache-restore-sif
        uses: actions/cache/restore@v4
        with:
          path: dependency_image.sif
          key: ${{ runner.os }}-apptainer-sif-${{ hashFiles('containers/Singularity.deps.def') }}

      - name: Build Dependency SIF (if cache miss)
        if: steps.cache-restore-sif.outputs.cache-hit != 'true'
        run: |
          echo "Cache miss. Building dependency_image.sif..."
          sudo apptainer build --force dependency_image.sif containers/Singularity.deps.def

      - name: Save Dependency SIF to Cache
        if: steps.cache-restore-sif.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: dependency_image.sif
          key: ${{ steps.cache-restore-sif.outputs.cache-primary-key || format('{0}-apptainer-sif-{1}', runner.os, hashFiles('containers/Singularity.deps.def')) }}

      - name: Compile Application Binaries
        run: |
          echo "Compiling application executables inside the dependency container..."
          sudo apptainer exec \
            --bind $PWD:/src \
            ./dependency_image.sif \
            bash -c 'source /opt/rh/gcc-toolset-11/enable && cd /src && make all -j$(nproc)'
          echo "Compilation complete."
      
      - name: Build Final Release SIF
        run: |
          echo "Building the final, clean application container for release..."
          SIF_FILENAME="openimpala-${{ github.ref_name }}.sif"
          STAGING_DIR=$(mktemp -d)
          echo "Using staging directory: $STAGING_DIR"

          echo "Copying compiled application binaries to staging area..."
          cp -r ./build/apps "$STAGING_DIR/"

          echo "Extracting runtime libraries with existence check and dereferencing symlinks..."
          sudo apptainer exec \
            --bind "$STAGING_DIR:/staging" \
            ./dependency_image.sif \
            bash -c '
              set -e
              
              paths_to_copy=("opt" "usr/local")
              valid_paths=""
              
              cd /
              
              for path in "${paths_to_copy[@]}"; do
                if [ -e "$path" ]; then
                  echo "Found path: /$path"
                  valid_paths="$valid_paths $path"
                else
                  echo "WARNING: Path /$path not found in container, skipping."
                fi
              done
              
              if [ -n "$valid_paths" ]; then
                # Use "h" flag to dereference symlinks and copy the files they point to
                echo "Archiving paths:$valid_paths"
                tar chf - $valid_paths | (cd /staging && tar xf -)
                echo "Extraction complete."
              else
                echo "No valid paths found to extract. Nothing to do."
              fi
            '
            
          echo "Creating final Singularity definition file..."
          cat > Singularity.final.def <<-EOF
          Bootstrap: docker
          From: quay.io/rockylinux/rockylinux:8

          %files
              "$STAGING_DIR/apps" /usr/bin/
              "$STAGING_DIR/opt" /
              "$STAGING_DIR/usr/local" /usr/

          %post
              # Configure the dynamic linker to find all necessary libraries.
              # This ensures the system loader can find everything without relying on environment variables.
              echo "/usr/local/lib" > /etc/ld.so.conf.d/01-openmpi.conf
              echo "/opt/rh/gcc-toolset-11/root/usr/lib64" > /etc/ld.so.conf.d/02-gcc-toolset-11.conf
              echo "/opt/amrex/25.03/lib" > /etc/ld.so.conf.d/03-amrex.conf
              echo "/opt/hypre/v2.32.0/lib" > /etc/ld.so.conf.d/04-hypre.conf
              echo "/opt/hdf5/1.12.3/lib" > /etc/ld.so.conf.d/05-hdf5.conf
              echo "/opt/libtiff/4.6.0/lib" > /etc/ld.so.conf.d/06-libtiff.conf
              ldconfig

          %environment
              export LC_ALL=C
              # Explicitly set the PATH to include the GCC Toolset compilers and custom binaries
              export PATH=/opt/rh/gcc-toolset-11/root/usr/bin:/usr/local/bin:${PATH}
              
              # Explicitly set LD_LIBRARY_PATH to include all custom and toolset libraries.
              # This provides a self-contained environment.
              export LD_LIBRARY_PATH=/opt/rh/gcc-toolset-11/root/usr/lib64:/opt/rh/gcc-toolset-11/root/usr/lib:/opt/amrex/25.03/lib:/opt/hypre/v2.32.0/lib:/opt/hdf5/1.12.3/lib:/opt/libtiff/4.6.0/lib:/usr/local/lib:${LD_LIBRARY_PATH}
          EOF

          echo "Building final SIF..."
          sudo apptainer build "$SIF_FILENAME" Singularity.final.def
          echo "SIF_FILENAME=$SIF_FILENAME" >> $GITHUB_ENV

      - name: Create GitHub Release and Upload SIF
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.SIF_FILENAME }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

