name: Build and Release Singularity Container

on:
  push:
    # This is the important part: only trigger on tags that look like versions.
    tags:
      - 'v*'
  workflow_dispatch: # Allows manual trigger via Actions tab

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.2.5

      - name: Build Apptainer containers
        run: |
          # Step 1: Build the dependency container as before.
          echo "Building dependency container..."
          sudo apptainer build dependency_image.sif containers/Singularity.deps.def

          # Step 2: Extract the compiled libraries to a temporary directory OUTSIDE the project folder.
          echo "Extracting libraries from dependency container..."
          # Use ../tmp_deps to create the directory one level up.
          mkdir -p ../tmp_deps/opt
          mkdir -p ../tmp_deps/usr/local
          sudo apptainer exec dependency_image.sif cp -a /opt/. ../tmp_deps/opt/
          sudo apptainer exec dependency_image.sif cp -a /usr/local/. ../tmp_deps/usr/local/
          
          # Step 3: Build the final application, bind-mounting the new path.
          echo "Building application container..."
          SIF_FILENAME="openimpala-${{ github.ref_name }}.sif"
          # The --bind flag now points to the path outside the current directory.
          sudo apptainer build --bind ../tmp_deps:/deps "$SIF_FILENAME" containers/Singularity.def

          # Step 4: Clean up the temporary directory.
          rm -rf ../tmp_deps

          echo "SIF_FILENAME=$SIF_FILENAME" >> $GITHUB_ENV

      - name: Create GitHub Release and Upload SIF Asset
        # This condition ensures the release step ONLY runs when a tag is pushed.
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.SIF_FILENAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Build Output
        run: |
          echo "Checking existence and size of ${{ env.SIF_FILENAME }}"
          ls -lh "${{ env.SIF_FILENAME }}"
          if [ ! -s "${{ env.SIF_FILENAME }}" ]; then
            echo "Error: Built SIF file is missing or empty."
            exit 1
          fi
          echo "Build verification step passed."
