name: Build and Release Singularity Container

on:
  push:
    # This is the important part: only trigger on tags that look like versions.
    tags:
      - 'v*'
  workflow_dispatch: # Allows manual trigger via Actions tab

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.2.5

      - name: Build Apptainer containers
        run: |
          # Step 1: Build the dependency container as before.
          echo "Building dependency container..."
          sudo apptainer build dependency_image.sif containers/Singularity.deps.def

          # Step 2: Define an ABSOLUTE path for the temp directory and extract the libraries.
          echo "Extracting libraries from dependency container..."
          # This creates an absolute path like '/home/runner/work/tmp_deps'
          DEPS_DIR=$(cd .. && pwd)/tmp_deps
          echo "Using temporary directory: $DEPS_DIR"
          
          mkdir -p "$DEPS_DIR/opt"
          mkdir -p "$DEPS_DIR/usr/local"
          sudo apptainer exec dependency_image.sif cp -a /opt/. "$DEPS_DIR/opt/"
          sudo apptainer exec dependency_image.sif cp -a /usr/local/. "$DEPS_DIR/usr/local/"
          
          # Step 3: Build the final application, binding the absolute path.
          echo "Building application container..."
          SIF_FILENAME="openimpala-${{ github.ref_name }}.sif"
          # The --bind flag now uses the absolute path variable.
          sudo apptainer build --bind "$DEPS_DIR:/deps" "$SIF_FILENAME" containers/Singularity.def

          # Step 4: Clean up using the absolute path.
          rm -rf "$DEPS_DIR"

          echo "SIF_FILENAME=$SIF_FILENAME" >> $GITHUB_ENV

      - name: Create GitHub Release and Upload SIF Asset
        # This condition ensures the release step ONLY runs when a tag is pushed.
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.SIF_FILENAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Build Output
        run: |
          echo "Checking existence and size of ${{ env.SIF_FILENAME }}"
          ls -lh "${{ env.SIF_FILENAME }}"
          if [ ! -s "${{ env.SIF_FILENAME }}" ]; then
            echo "Error: Built SIF file is missing or empty."
            exit 1
          fi
          echo "Build verification step passed."
